MVC_Library/Controllers/MessagesController.cs
using MVC_Library.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Library.Controllers
{
    public class MessagesController : Controller
    {
        Db_LibraryEntities db = new Db_LibraryEntities();
        // GET: Messages
        public ActionResult Index()
        {
            var user = (string)Session["Mail"].ToString();
            var values = db.TblMessages.Where(x => x.messageReceiver == user).ToList();
            return View(values);
        }

        public ActionResult Index2()
        {
            var user = (string)Session["Mail"].ToString();
            var values = db.TblMessages.Where(x => x.messageSender == user).ToList();
            return View(values);
        }

        [HttpGet]
        public ActionResult New()
        {
            return View();
        }

        [HttpPost]
        public ActionResult New(TblMessage p)
        {
            var user = (string)Session["Mail"];
            db.TblMessages.Add(p);
            p.messageSender = user;
            p.messageDate = DateTime.Now;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MVC_Library/Views/Messages/Index.cshtml
@using MVC_Library.Models.Entity
@model List<TblMessage>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_StudentLayout.cshtml";
}


<h3>Received Message List</h3>
<table class="table table-bordered">
    <tr>
        <th>Sender</th>
        <th>Subject</th>
        <th>Message</th>
        <th>Operation</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.messageSender</td>
            <td>@item.messageSubject</td>
            <td>@item.messageContaext</td>
        </tr>
    }
</table>
<a href="/Messages/New/" class="btn btn-info">New Message</a>

MVC_Library/Views/Messages/Index2.cshtml
@using MVC_Library.Models.Entity
@model List<TblMessage>

@{
    ViewBag.Title = "Index2";
    Layout = "~/Views/Shared/_StudentLayout.cshtml";
}

<h3>Sended Message List</h3>
<table class="table table-bordered">
    <tr>
        <th>Receiver</th>
        <th>Subject</th>
        <th>Message</th>
        <th>Operation</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.messageReceiver</td>
            <td>@item.messageSubject</td>
            <td>@item.messageContaext</td>
        </tr>
    }
</table>

MVC_Library/Views/Messages/New.cshtml
@{
    ViewBag.Title = "New";
    Layout = "~/Views/Shared/_StudentLayout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
        }

        * {
            box-sizing: border-box;
        }

        input[type=text], select, textarea {
            width: 100%;
            padding: 12px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
            margin-top: 6px;
            margin-bottom: 16px;
            resize: vertical;
        }

        input[type=submit] {
            background-color: #04AA6D;
            color: white;
            padding: 12px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

            input[type=submit]:hover {
                background-color: #45a049;
            }

        .container {
            border-radius: 5px;
            background-color: #f2f2f2;
            padding: 20px;
        }
    </style>
</head>
<body>

    <h3>Message Form</h3>

    <div class="container">
        @using (Html.BeginForm("New","Messages",FormMethod.Post))
            {

            <label for="fname">Receiver E-Mail</label>
            <input type="text" id="fname" name="messageReceiver" placeholder="Receiver E-Mail Address">

            <label for="lname">Subject</label>
            <input type="text" id="lname" name="messageSubject" placeholder="Subject">

            <label for="subject">Context</label>
            <textarea id="subject" name="messageContaext" placeholder="Context" style="height:200px"></textarea>

            <input type="submit" value="SEND">
        }
    </div>

</body>
</html>