MVC_Library/Controllers/AuthorController.cs
using MVC_Library.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Library.Controllers
{
    public class AuthorController : Controller
    {
        Db_LibraryEntities db = new Db_LibraryEntities();
        // GET: Author
        public ActionResult Index()
        {
            var values = db.TblAuthors.ToList();
            return View(values);
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Add(TblAuthor tbl)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            else
            {
                db.TblAuthors.Add(tbl);
                db.SaveChanges();
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            var value = db.TblAuthors.Find(id);
            db.TblAuthors.Remove(value);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var value = db.TblAuthors.Find(id);
            return View(value);
        }
        [HttpPost]
        public ActionResult Edit(TblAuthor tbl)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            else
            {
                var value = db.TblAuthors.Find(tbl.authorId);
                value.authorName = tbl.authorName;
                value.authorSurname = tbl.authorSurname;
                value.authorDetails = tbl.authorDetails;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }
    }
}

MVC_Library/Views/Author/Add.cshtml
@model MVC_Library.Models.Entity.TblAuthor
@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<form class="form-group" method="post">
    <div>
        <label>Author Name</label>
        <input type="text" class="form-control" name="authorName" />
        @Html.ValidationMessageFor(y => y.authorName)
    </div>
    <div>
        <label>Author Name</label>
        <input type="text" class="form-control" name="authorSurname" />
        @Html.ValidationMessageFor(y => y.authorSurname)
    </div>
    <div>
        <label>Details</label>
        <input type="text" class="form-control" name="authorDetails" />
    </div>
    <div style="margin-top:10px">
        <button class="btn btn-success">SAVE</button>
    </div>
</form>

MVC_Library/Views/Author/Edit.cshtml
@model MVC_Library.Models.Entity.TblAuthor
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("Edit", "Author", FormMethod.Post))
{
    <div class="form-group">
        <label>Author Name</label>
        @Html.TextBoxFor(m => m.authorName, new { @class = "form-control" })
        @Html.ValidationMessageFor(y => y.authorName)
    </div>
    <div class="form-group">
        <label>Author Surname</label>
        @Html.TextBoxFor(m => m.authorSurname, new { @class = "form-control" })
        @Html.ValidationMessageFor(y => y.authorSurname)
    </div>
    <div class="form-group">
        <label>Details</label>
        @Html.TextBoxFor(m => m.authorDetails, new { @class = "form-control" })
    </div>
    @Html.HiddenFor(m => m.authorId)
    <div style="margin-top:10px">
        <button class="btn btn-success">UPDATE</button>
    </div>
}

MVC_Library/Views/Author/Index.cshtml
@using MVC_Library.Models.Entity
@model List<TblAuthor>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Author List</h2>
<br />
<table class="table table-bordered">
    <tr style="background-color:rgb(252, 178, 22)">
        <th>#</th>
        <th>Name</th>
        <th>Surname</th>
        <th>Details</th>
        <th>Operations</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.authorId</td>
            <td>@item.authorName</td>
            <td>@item.authorSurname</td>
            <td>@item.authorDetails</td>
            <td>
                <a href="/Author/Edit/@item.authorId" class="btn btn-warning">Update</a>
                <a href="/Author/Delete/@item.authorId" class="btn btn-danger">Delete</a>
            </td>
        </tr>
    }
</table>
<a href="/Author/Add/" class="btn btn-success">Add New Category</a>